name: Bug report
description: Report an unexpected behavior of existing configs
labels: [bug]
body:
  - type: checkboxes
    id: guidelines
    attributes:
      label: Contributing guidelines
      options:
      - label: I reproduced this on latest version of the `main` branch
        required: true
  - type: dropdown
    id: nvim-version
    attributes:
      label: "Neovim version"
      description: "Choose the latest Neovim version on which you can reproduce the problem"
      multiple: false
      options:
        - 0.9.x
        - 0.10.x
        - 0.11.x
        - 0.12 (!at least latest Nightly build!)
      default: 2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A short description of a problem; include expected behavior"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction"
      description: "Steps to reproduce the issue. Steps should assume that only clean set up was just done."
    validations:
      required: true
